package org.intelehealth.abdm.enums

enum class AbdmOutcomes {
    NAVIGATE_TO_IDENTIFICATION_SCREEN_WITH_EXISTING_DETAILS,
    NAVIGATE_TO_IDENTIFICATION_SCREEN_FOR_NEW_PATIENT,
    NAVIGATE_TO_IDENTIFICATION_SCREEN_AFTER_ABHA_SUGGESTIONS,
}