package org.intelehealth.abdm.abha_suggestions;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputFilter;
import android.text.Spanned;
import android.text.TextUtils;
import android.text.TextWatcher;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.view.ViewCompat;

import com.github.ajalt.timberkt.Timber;
import com.google.android.material.chip.Chip;
import com.google.android.material.chip.ChipGroup;

import org.intelehealth.abdm.constants.AbdmConstant;
import org.intelehealth.abdm.databinding.ActivityAbhaAddressSuggestionsBinding;
import org.intelehealth.abdm.dialog.AbhaAddressSuggestionDialogFragment;
import org.intelehealth.abdm.enums.AbdmOutcomes;
import org.intelehealth.abdm.model.AbdmResult;
import org.intelehealth.abdm.model.EnrollSuggestionRequestBody;
import org.intelehealth.abdm.model.OTPVerificationResponse;
import org.intelehealth.abdm.model.SetAbhaAddressResponse;
import org.intelehealth.abdm.model.UpdateIdentifierReqBody;
import org.intelehealth.abdm.restapi.RetrofitProvider;
import org.intelehealth.abdm.utils.AbdmManager;
import org.intelehealth.abdm.utils.SnackBarUtils;
import org.intelehealth.abdm.utils.UuidDictionary;
import org.intelehealth.abdm.utils.WindowUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.reactivex.Single;
import io.reactivex.android.schedulers.AndroidSchedulers;
import io.reactivex.observers.DisposableSingleObserver;
import io.reactivex.schedulers.Schedulers;
import okhttp3.ResponseBody;
import retrofit2.Response;

import org.intelehealth.abdm.R;

public class AbhaAddressSuggestionsActivity extends AppCompatActivity {
    private final Context context = AbhaAddressSuggestionsActivity.this;
    public static final String TAG = AbhaAddressSuggestionsActivity.class.getSimpleName();
    ActivityAbhaAddressSuggestionsBinding binding;
    private String accessToken;
    private Boolean firstRequestFulfilled;

    private OTPVerificationResponse otpVerificationResponse;
    SnackBarUtils snackbarUtils;
    private String blockCharacterSetABHAAddress = "@";
    private String initialAbhaAddress;
    EditText abhaAddressET;

    private boolean isProgrammaticTextChange = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityAbhaAddressSuggestionsBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());
        WindowUtils.setStatusBarColor(AbhaAddressSuggestionsActivity.this);  // changing status bar color
        snackbarUtils = new SnackBarUtils();
        abhaAddressET = binding.etAbhaAddress;

        Intent intent = getIntent();
        accessToken = intent.getStringExtra("accessToken");
        otpVerificationResponse = (OTPVerificationResponse) intent.getSerializableExtra("payload");
        firstRequestFulfilled = intent.getBooleanExtra("firstRequestFulfilled", false);

        if (otpVerificationResponse.getABHAProfile() != null) {
            initialAbhaAddress = otpVerificationResponse.getABHAProfile().getPhrAddress().get(0);
        }

        if (intent.hasExtra("addressList")) {
            ArrayList<String> phrAddressSuggestionsList = intent.getStringArrayListExtra("addressList");
            if (phrAddressSuggestionsList != null) {
                for (String phrAddressAutoGenerated : phrAddressSuggestionsList) {
                    createDynamicChips(phrAddressAutoGenerated);
                }
            }
        }

        binding.chipGrp.setOnCheckedChangeListener(new ChipGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(ChipGroup group, int checkedId) {
                if (checkedId != View.NO_ID) {
                    Chip chip = group.findViewById(checkedId);
                    if (chip != null) {
                        isProgrammaticTextChange = true; // Set the flag
                        abhaAddressET.setText(chip.getText().toString());
                    }
                }
            }
        });

        abhaAddressET.addTextChangedListener(new TextWatcher() {

            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                abhaAddressET.setTextColor(getResources().getColor(R.color.primary_text));
            }

            @Override
            public void afterTextChanged(Editable s) {
                if (isProgrammaticTextChange) {
                    // This change came from code (chip selected), don't clear chip
                    isProgrammaticTextChange = false;
                    return;
                }

                // User is editing manually — clear chip selection
                if (binding.chipGrp.getCheckedChipId() != View.NO_ID) {
                    binding.chipGrp.clearCheck();
                }
            }
        });

        binding.submitABHAAddressBtn.setOnClickListener(v -> {
//            resetPhrAddresses();

            Chip chip = binding.chipGrp.findViewById(binding.chipGrp.getCheckedChipId());
            String selectedChip = chip != null ? chip.getText().toString() : "";
            abhaAddressET.setFilters(new InputFilter[]{filter});
            String abhaAddress = Objects.requireNonNull(abhaAddressET.getText()).toString();

            if (TextUtils.isEmpty(selectedChip) && TextUtils.isEmpty(abhaAddress)) {
                Toast.makeText(context, getString(R.string.please_select_abha_address), Toast.LENGTH_SHORT).show();
            } else if (!TextUtils.isEmpty(selectedChip)) {
                callSetPreferredABHAAddressAPI(selectedChip);
            } else {
                if (isValidAbhaAddress(abhaAddress)) {
                    callSetPreferredABHAAddressAPI(abhaAddress);
                    abhaAddressET.setTextColor(getResources().getColor(R.color.green3));
                } else {
                    abhaAddressET.setTextColor(getResources().getColor(R.color.red));
                }
            }
        });
        binding.ivAbhaSuggestion.setOnClickListener(v -> {
            AbhaAddressSuggestionDialogFragment abhaAddressSuggestionDialogFragment = new AbhaAddressSuggestionDialogFragment();
            abhaAddressSuggestionDialogFragment.show(getSupportFragmentManager(), "");
        });
    }

    private void resetPhrAddresses() {
        List<String> phrAddressesList = new ArrayList<>();
        phrAddressesList.add(initialAbhaAddress);
        otpVerificationResponse.getABHAProfile().setPhrAddress(phrAddressesList);
    }

    private InputFilter filter = new InputFilter() {
        @Override
        public CharSequence filter(CharSequence source, int start, int end, Spanned dest, int dstart, int dend) {
            if (source != null && blockCharacterSetABHAAddress.contains(("" + source))) {
                return "";
            }
            return null;
        }
    };

    public boolean isValidAbhaAddress(String text) {
        // Check for @abdm presence
        String suffix = "@abdm";
        String prefix = text;

        if (text.contains(suffix)) {
            if (!text.endsWith(suffix)) {
                // '@abdm' is somewhere in the middle
                Toast.makeText(context, getString(R.string.abdm_suffix_is_only_allowed_at_the_end), Toast.LENGTH_SHORT).show();
                return false;
            }

            int count = (text.length() - text.replace(suffix, "").length()) / suffix.length();
            if (count > 1) {
                Toast.makeText(context, getString(R.string.abdm_suffix_can_only_appear_once), Toast.LENGTH_SHORT).show();
                return false;
            }

            prefix = text.substring(0, text.length() - suffix.length());
        }


        // Validate length of the prefix
        if (prefix.length() < 8 || prefix.length() > 18) {
            snackbarUtils.showSnackLinearLayoutParentSuccess(context, binding.llActionBar, getString(R.string.length_validation), false);
            return false;
        }

        if (!prefix.matches("^[A-Za-z0-9._]+$")) {
            snackbarUtils.showSnackLinearLayoutParentSuccess(context, binding.llActionBar, getString(R.string.characters_validation), false);
            return false;
        }

        if (prefix.startsWith(".") || prefix.startsWith("_") || prefix.endsWith(".") || prefix.endsWith("_")) {
            snackbarUtils.showSnackLinearLayoutParentSuccess(context, binding.llActionBar, getString(R.string.special_characters_position_validation), false);
            return false;
        }

        if (!doSpecialCharactersExistOnce(prefix)) {
            snackbarUtils.showSnackLinearLayoutParentSuccess(context, binding.llActionBar, getString(R.string.special_characters_count_validation), false);
            return false;
        }

        return true;
    }

    private boolean doSpecialCharactersExistOnce(String abhaAddress) {
        int countDot = 0;
        int countUnderscore = 0;
        char[] characterArray = abhaAddress.toCharArray();

        for (char current : characterArray) {
            if (current == '.') countDot++;
            if (current == '_') countUnderscore++;
        }

        return (countDot <= 1 && countUnderscore <= 1);
    }

    private void callSetPreferredABHAAddressAPI(String selectedChip) {
        if (!selectedChip.isEmpty()) {   // here you set this value to the Setter of the response variable and pass it to identification screen.
            if (selectedChip.equalsIgnoreCase(otpVerificationResponse.getABHAProfile().getPhrAddress().get(0))) {
                AbdmResult resultData = new AbdmResult(
                        AbdmOutcomes.NAVIGATE_TO_IDENTIFICATION_SCREEN_AFTER_ABHA_SUGGESTIONS_FOR_CREATION,
                        accessToken,
                        null,
                        otpVerificationResponse,
                        null
                );

                Intent resultIntent = new Intent();
                resultIntent.putExtra(AbdmConstant.INTENT_ABDM_RESULT, resultData);
                setResult(RESULT_OK, resultIntent);
                finish();
                return;
            } else {
                List<String> phrAddrList = new ArrayList<>();
                phrAddrList.add(selectedChip);
                phrAddrList.addAll(otpVerificationResponse.getABHAProfile().getPhrAddress());
                otpVerificationResponse.getABHAProfile().setPhrAddress(phrAddrList);
            }
        }

        EnrollSuggestionRequestBody body = new EnrollSuggestionRequestBody();
        body.setTxnId(otpVerificationResponse.getTxnId());
        body.setAbhaAddress(selectedChip);
        Single<Response<SetAbhaAddressResponse>> setPhrAddressResponse = RetrofitProvider.getApiService().setPreferredAbhaAddress(accessToken, body);
        setPhrAddressResponse
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new DisposableSingleObserver<>() {
                    @Override
                    public void onSuccess(Response<SetAbhaAddressResponse> setAbhaAddressResponseResponse) {
                        if (otpVerificationResponse.getUuID() != null) {
                            updatePatientIdentifier(otpVerificationResponse, setAbhaAddressResponseResponse);
                        } else {
                            handleSuccess(setAbhaAddressResponseResponse);
                        }
                    }

                    @Override
                    public void onError(Throwable e) {
                        Timber.tag(TAG).e("onError: onSuccess: callSetPreferredABHAAddressAPI%s", e.getMessage());
                    }
                });
    }

    private void updatePatientIdentifier(OTPVerificationResponse abhaProfileResponse, Response<SetAbhaAddressResponse> setAbhaAddressResponseResponse) {
        if (setAbhaAddressResponseResponse != null && setAbhaAddressResponseResponse.body() != null) {
            String newAbhaAddress = setAbhaAddressResponseResponse.body().getPreferredAbhaAddress();

            UpdateIdentifierReqBody requestBody = new UpdateIdentifierReqBody();
            requestBody.setIdentifier(newAbhaAddress);
            requestBody.setIdentifierType(UuidDictionary.UPDATE_IDENTIFIER_TYPE_UUID);
            requestBody.setLocation(AbdmManager.getLocationUuid());
            Single<Response<ResponseBody>> responseSingle = RetrofitProvider.getApiService().updatePatientIdentifier(
                    abhaProfileResponse.getUuID(),
                    "Basic " + AbdmManager.getEncoded(),
                    requestBody
            );

            responseSingle.subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new DisposableSingleObserver<>() {
                        @Override
                        public void onSuccess(Response<ResponseBody> response) {
                            handleSuccess(setAbhaAddressResponseResponse);
                        }

                        @Override
                        public void onError(Throwable e) {
                        }
                    });
        }
    }


    private void handleSuccess(Response<SetAbhaAddressResponse> setAbhaAddressResponseResponse) {
        if (setAbhaAddressResponseResponse.code() == 200) {// ie. setting this new abha address is done.
            try {
                abhaAddressET.setTextColor(getResources().getColor(R.color.green3));
                AbdmManager.setPreferredAddressSet(true);
                Toast.makeText(context, getString(R.string.preferred_abha_address_is_set_successfully), Toast.LENGTH_SHORT).show();

                if (setAbhaAddressResponseResponse.body() != null) {
                    String preferredAbhaAddress = setAbhaAddressResponseResponse.body().getPreferredAbhaAddress();
                    String preferredAbhaAddressWithoutSbx = preferredAbhaAddress.replaceAll("@abdm", "");
                    List<String> phrAddresses = otpVerificationResponse.getABHAProfile().getPhrAddress();
                    phrAddresses.remove(preferredAbhaAddressWithoutSbx);

                    if (!preferredAbhaAddress.endsWith("@abdm")) {
                        preferredAbhaAddress = preferredAbhaAddress.concat("@abdm");
                    }

                    phrAddresses.add(0, preferredAbhaAddress);
                    AbdmResult resultData = new AbdmResult(
                            AbdmOutcomes.NAVIGATE_TO_IDENTIFICATION_SCREEN_AFTER_ABHA_SUGGESTIONS_FOR_CREATION,
                            accessToken,
                            null,
                            otpVerificationResponse,
                            null
                    );

                    Intent resultIntent = new Intent();
                    resultIntent.putExtra(AbdmConstant.INTENT_ABDM_RESULT, resultData);
                    setResult(RESULT_OK, resultIntent);
                    finish();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (setAbhaAddressResponseResponse.code() == 409) {
            abhaAddressET.setTextColor(getResources().getColor(R.color.red));
            Toast.makeText(context, "This ABHA address already exists, please use a different one", Toast.LENGTH_SHORT).show();
        } else {
            abhaAddressET.setTextColor(getResources().getColor(R.color.red));
            Toast.makeText(context, setAbhaAddressResponseResponse.raw().message(), Toast.LENGTH_SHORT).show();
        }
    }

    private void createDynamicChips(String chipTitle) {
        Chip chip = new Chip(context);
        chip.setId(ViewCompat.generateViewId());
        chip.setText(chipTitle);
        chip.setCheckable(true);
        chip.setChipBackgroundColorResource(R.color.iconTintWhite);
        chip.setChipStrokeColorResource(R.color.colorPrimaryDark);
        chip.setChipStrokeWidth(2);
        chip.setTextColor(getColor(R.color.colorPrimary));
        chip.isCloseIconVisible();
        chip.setCheckedIconTintResource(R.color.colorPrimary);
        binding.chipGrp.addView(chip);
    }

    @SuppressLint("MissingSuperCall")
    @Override
    public void onBackPressed() {
        //  super.onBackPressed();
        snackbarUtils.showSnackConstraintLayoutParentSuccess(context, binding.layoutParent, getString(R.string.please_click_on_submit_button_to_proceed), true);
    }
}