package org.intelehealth.app.ui.draftsurvey.utils

enum class HouseholdSurveyAttributes(val key: String) {
    NAME_PRIMARY_RESPONDENT("NamePrimaryRespondent"),
    HOUSEHOLD_NUMBER("HouseholdNumber"),
    HOUSE_STRUCTURE("HouseStructure"),
    RESULT_OF_VISIT("ResultOfVisit"),
    HOUSEHOLD_HEAD_NAME("householdHeadName"),
    HOUSEHOLD_HEAD_RELIGION("householdHeadReligion"),
    HOUSEHOLD_HEAD_CASTE("householdHeadCaste"),
    NO_OF_SMARTPHONES("noOfSmartphones"),
    NO_OF_FEATURE_PHONES("noOfFeaturePhones"),
    NO_OF_EARNING_MEMBERS("noOfEarningMembers"),
    PRIMARY_SOURCE_OF_INCOME("primarySourceOfIncome"),
    HOUSEHOLD_ELECTRICITY_STATUS("householdElectricityStatus"),
    NO_OF_LOAD_SHEDDING_HRS_PER_DAY("noOfLoadSheddingHrsPerDay"),
    NO_OF_LOAD_SHEDDING_HRS_PER_WEEK("noOfLoadSheddingHrsPerWeek"),
    RUNNING_WATER_STATUS("runningWaterStatus"),
    PRIMARY_SOURCE_OF_RUNNING_WATER("primarySourceOfRunningWater"),
    WATER_SOURCE_DISTANCE("waterSourceDistance"),
    WATER_SUPPLY_AVAILABILITY_HRS_PER_DAY("waterSupplyAvailabilityHrsPerDay"),
    WATER_SUPPLY_AVAILABILITY_DAYS_PER_WEEK("waterSupplyAvailabilityDaysperWeek"),
    HOUSEHOLD_BANK_ACCOUNT_STATUS("householdBankAccountStatus"),
    HOUSEHOLD_CULTIVABLE_LAND("householdCultivableLand"),
    AVERAGE_ANNUAL_HOUSEHOLD_INCOME("averageAnnualHouseholdIncome"),
    MONTHLY_FOOD_EXPENDITURE("monthlyFoodExpenditure"),
    ANNUAL_HEALTH_EXPENDITURE("annualHealthExpenditure"),
    ANNUAL_EDUCATION_EXPENDITURE("annualEducationExpenditure"),
    ANNUAL_CLOTHING_EXPENDITURE("annualClothingExpenditure"),
    MONTHLY_INTOXICANTS_EXPENDITURE("monthlyIntoxicantsExpenditure"),
    HOUSEHOLD_BPL_CARD_STATUS("householdBPLCardStatus"),
    HOUSEHOLD_ANTODAYA_CARD_STATUS("householdAntodayaCardStatus"),
    HOUSEHOLD_RSBY_CARD_STATUS("householdRSBYCardStatus"),
    HOUSEHOLD_MGNREGA_CARD_STATUS("householdMGNREGACardStatus"),
    COOKING_FUEL_TYPE("cookingFuelType"),
    MAIN_LIGHTING_SOURCE("mainLightingSource"),
    MAIN_DRINKING_WATER_SOURCE("mainDrinkingWaterSource"),
    SAFER_WATER_PROCESS("saferWaterProcess"),
    HOUSEHOLD_TOILET_FACILITY("householdToiletFacility"),
    HOUSEHOLD_OPEN_DEFECATION_STATUS("householdOpenDefecationStatus"),
    FOOD_ITEMS_PREPARED_IN_TWENTY_FOUR_HRS("foodItemsPreparedInTwentyFourHrs"),
    SUB_CENTRE_DISTANCE("subCentreDistance"),
    NEAREST_PRIMARY_HEALTH_CENTER_DISTANCE("nearestPrimaryHealthCenterDistance"),
    NEAREST_COMMUNITY_HEALTH_CENTER_DISTANCE("nearestCommunityHealthCenterDistance"),
    NEAREST_DISTRICT_HOSPITAL_DISTANCE("nearestDistrictHospitalDistance"),
    NEAREST_PATHOLOGICAL_LAB_DISTANCE("nearestPathologicalLabDistance"),
    NEAREST_PRIVATE_CLINIC_MBBS_DOCTOR("nearestPrivateClinicMBBSDoctor"),
    NEAREST_PRIVATE_CLINIC_ALTERNATE_MEDICINE("nearestPrivateClinicAlternateMedicine"),
    NEAREST_TERTIARY_CARE_FACILITY("nearestTertiaryCareFacility");

    companion object {
        fun getAllKeys() = entries.map { it.key }
    }
}